### ISSUE TITLE
Function hook not working: Unable to proceed because of [object Object] in params field

### ISSUE THREAD

**Issue by RoskiDeluge** [dijonmusters/build-a-saas-with-next-js-supabase-and-stripe#1]
Hello, 

Great tutorial so far. Just wanted to give a heads up on an error that is a blocker for this point in the tutorial. 
On the Supabase backend when I try to add `API_ROUTE_SECRET` to the Http params field, the value field pre-populates with `[object Object]` and I'm not able to either override it or save the param to make the function hook work. 

Here's a screen grab:
![object_error](https://user-images.githubusercontent.com/5524486/145308715-c0c2743c-ddf5-4b66-a57a-7a55de1bd2f2.png)

**Comment by 6laercio** [comment]
Try to add a new one and delete the first one.

![image](https://user-images.githubusercontent.com/18237035/145389826-9282ef2e-84a3-48e9-93f4-56456712ea8d.png)

**Comment by RoskiDeluge** [comment]
Thanks @laercio-co it worked!
